version: '3.8'

networks:
  http_network:
    name: http_network
    driver: bridge
    external: true

volumes:
  mysql-volume:
    driver: local

services:
  mysql:
    image: mysql/mysql-server:8.0
    platform: linux/amd64
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - http_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    security_opt:
      - no-new-privileges:true
    links:
      - mysql:mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_USERNAME: "${DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      PMA_ABSOLUTE_URI: https://$MAIN_DOMAIN
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=http_network"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=le-dns"
      - "traefik.http.routers.phpmyadmin.rule=Host(`$MAIN_DOMAIN`)"
    depends_on:
      - mysql
    networks:
      - http_network
